image: elixir:1.8

services:
  - postgres:latest

variables:
  POSTGRES_DB: balance_test
  POSTGRES_USER: balance_test
  POSTGRES_PASSWORD: "balance"
  POSTGRES_HOST: postgres

stages:
  - connect
  - build
  - test

connect-db:
  image: postgres:latest
  stage: connect
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

build-dev:
  stage: build
  variables:
    MIX_ENV: test
  cache:
    paths:
      - deps/
      - _build/
  script:
    - make init
    - make compile
  environment:
    name: develop
  only:
    - develop
    - /^release.*$/
    - /^hotfix.*$/
  dependencies:
    - connect-db

test-models-balance:
  stage: test
  cache:
    paths:
      - deps/
      - _build/
  script:
    - MIX_ENV=test make test
    - MIX_ENV=test mix coveralls
  dependencies:
    - build-dev
    - build-prod
    - connect-db

build-prod:
  stage: build
  variables:
    MIX_ENV: prod
  cache:
    paths:
      - deps/
      - _build/
  script:
    - make init
    - make compile
  environment:
    name: production
  only:
    - master
  dependencies:
    - connect-db
