image: trenpixster/elixir:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: balance_test
  POSTGRES_USER: balance_test
  POSTGRES_PASSWORD: "balance"
  POSTGRES_HOST: postgres

stages:
  - connect
  - build
  - test

connect-db:
  image: postgres:latest
  stage: connect
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

build-dev:
  stage: build
  services:
    - postgres:latest
  cache:
    paths:
      - deps/
      - _build/
  before-script:
    - apt-get update && apt-get -y install postgresql-client
  script:
    - MIX_ENV=test make init
    - MIX_ENV=test make compile
  environment:
    name: develop
  only:
    - develop
    - /^release.*$/
    - /^hotfix.*$/
  dependencies:
    - connect-db

test-models-balance:
  stage: test
  services:
    - postgres:latest
  cache:
    paths:
      - deps/
      - _build/
  script:
    - MIX_ENV=test make test
  dependencies:
    - build-dev
    - build-prod
    - connect-db

build-prod:
  stage: build
  services:
    - postgres:latest
  cache:
    paths:
      - deps/
      - _build/
  before-script:
    - apt-get update && apt-get -y install postgresql-client
  script:
    - MIX_ENV=test make init
    - MIX_ENV=test make compile
  environment:
    name: production
  only:
    - master
  dependencies:
    - connect-db
