language: elixir
elixir: 1.8

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master
  - develop

services:
  - postgresql

install:
- make init

script:
- make compile
- make test

notifications:
  email: false

