language: elixir
elixir: 1.8

cache:
  directories:
    - _build
    - deps

branches:
  only:
  - master
  - develop

services:
  - postgresql

postgres:
  adapter: postgresql
  database: balance_test
  username: postgres

before_script:
  - psql -c "CREATE USER balance_test WITH PASSWORD 'balance';" -U postgres
  - "psql -c 'ALTER USER balance_test CREATEDB;' -U postgres"
  - "psql -c 'GRANT ALL PRIVILEGES ON DATABASE balance_test TO balance_test;' -U postgres"
  - "psql -c 'CREATE DATABASE balance_test OWNER balance_test;' -U postgres"

script:
- make compile
- make test

notifications:
  email: false

