Balance.Repo.insert!(%Settings.Bonus{kind: "team", percent: 0.5})
Balance.Repo.insert!(%Settings.Bonus{kind: "individual", percent: 0.5})
Balance.Repo.insert!(%Settings.Goal{level: "A", goals: 5, team: "all"})
Balance.Repo.insert!(%Settings.Goal{level: "B", goals: 10, team: "all"})
Balance.Repo.insert!(%Settings.Goal{level: "C", goals: 15, team: "all"})
Balance.Repo.insert!(%Settings.Goal{level: "Cuauh", goals: 20, team: "all"})
Balance.Repo.insert!(%Settings.Goal{level: "A", goals: 5, team: "rojo"})
Balance.Repo.insert!(%Settings.Goal{level: "B", goals: 10, team: "rojo"})
Balance.Repo.insert!(%Settings.Goal{level: "C", goals: 15, team: "rojo"})
Balance.Repo.insert!(%Settings.Goal{level: "Cuauh", goals: 20, team: "rojo"})
Balance.Repo.insert!(%Settings.Goal{level: "A", goals: 5, team: "azul"})
Balance.Repo.insert!(%Settings.Goal{level: "B", goals: 10, team: "azul"})
Balance.Repo.insert!(%Settings.Goal{level: "C", goals: 15, team: "azul"})
Balance.Repo.insert!(%Settings.Goal{level: "Cuauh", goals: 20, team: "azul"})
