Balance.Repo.insert!(%Balance.Settings.Bonus{kind: "team", percent: 0.5})
Balance.Repo.insert!(%Balance.Settings.Bonus{kind: "individual", percent: 0.5})
Balance.Repo.insert!(%Balance.Settings.Goal{level: "A", goals: 5, team: "all"})
Balance.Repo.insert!(%Balance.Settings.Goal{level: "B", goals: 10, team: "all"})
Balance.Repo.insert!(%Balance.Settings.Goal{level: "C", goals: 15, team: "all"})
Balance.Repo.insert!(%Balance.Settings.Goal{level: "Cuauh", goals: 20, team: "all"})
